# Generated by Django 6.0.4 on 2026-04-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicdata',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('musicdata', models.BinaryField()),
            ],
            options={
                'db_table': 'musicdata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Objectdata',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('imagedata', models.BinaryField()),
            ],
            options={
                'db_table': 'objectdata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(default='John Doe', max_length=30)),
                ('profilePicture', models.ImageField(default='pfp/default.png', upload_to='pfp')),
            ],
            options={
                'db_table': 'userinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userpass',
            fields=[
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.userinfo')),
                ('password', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'db_table': 'userpass',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendid', models.IntegerField()),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='users.userinfo')),
            ],
            options={
                'db_table': 'friends',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomitem1id', models.IntegerField(blank=True, null=True)),
                ('roomitem2id', models.IntegerField(blank=True, null=True)),
                ('roomitem3id', models.IntegerField(blank=True, null=True)),
                ('roomitem4id', models.IntegerField(blank=True, null=True)),
                ('roomitem5id', models.IntegerField(blank=True, null=True)),
                ('backgroundid', models.ForeignKey(db_column='backgroundid', on_delete=django.db.models.deletion.DO_NOTHING, to='users.objectdata')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='users.userinfo')),
            ],
            options={
                'db_table': 'userroom',
                'managed': True,
            },
        ),
    ]
