# Generated by Django 5.2.13 on 2026-04-10 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendID', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundID', models.IntegerField()),
                ('roomItem1ID', models.IntegerField()),
                ('roomItem2ID', models.IntegerField()),
                ('roomItem3ID', models.IntegerField()),
                ('roomItem4ID', models.IntegerField()),
                ('roomItem5ID', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
            ],
        ),
    ]
