# Generated by Django 5.2.13 on 2026-04-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='hide_room',
            field=models.BooleanField(default=False),
        ),
    ]
