# Generated by Django 6.0.4 on 2026-04-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friends',
            table='friends',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
        migrations.AlterModelTable(
            name='userroom',
            table='userroom',
        ),
    ]
