# Generated by Django 5.2.13 on 2026-04-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinfo_hide_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='allow_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='show_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='show_status',
            field=models.BooleanField(default=True),
        ),
    ]
