# Generated by Django 5.2.13 on 2026-04-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userinfo_allow_requests_userinfo_show_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='show_status',
        ),
    ]
