# Generated by Django 5.2.13 on 2026-05-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userinfo_show_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroom',
            name='backgroundid',
        ),
        migrations.RemoveField(
            model_name='userroom',
            name='roomitem1id',
        ),
        migrations.RemoveField(
            model_name='userroom',
            name='roomitem2id',
        ),
        migrations.RemoveField(
            model_name='userroom',
            name='roomitem3id',
        ),
        migrations.RemoveField(
            model_name='userroom',
            name='roomitem4id',
        ),
        migrations.RemoveField(
            model_name='userroom',
            name='roomitem5id',
        ),
        migrations.RemoveField(
            model_name='userroom',
            name='userid',
        ),
        migrations.AddField(
            model_name='userroom',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
