# Generated by Django 5.2.13 on 2026-05-01 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userroom_backgroundid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroom',
            name='id',
        ),
        migrations.AddField(
            model_name='userroom',
            name='roomJSON',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userroom',
            name='userid',
            field=models.OneToOneField(db_column='userid', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='room', serialize=False, to='users.userinfo'),
            preserve_default=False,
        ),
    ]
